version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-multi-gateway-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - api-network
    depends_on:
      - db
      - gateway-mock
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=api_multi_gateway
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "8000:8000"
    command: sh -c "composer install --no-interaction && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: api-multi-gateway-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: api_multi_gateway
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - api-network
    ports:
      - "3306:3306"

  gateway-mock:
    image: matheusprotzen/gateways-mock
    container_name: api-multi-gateway-mock
    restart: unless-stopped
    ports:
      - "3001:3001"
      - "3002:3002"
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  dbdata:
    driver: local

